### PR TITLE
expand generic type/lt impl

### PR DESCRIPTION
**Pull request by demfabris**
Here we simply add support for generic parameters and lifetimes so the expanded macro compiles successfully

### CODE REVIEW

**Comment by tobiemh** [comment]
Nice one @demfabris ! Out of interest how will the macro be applied/specified in the main surrealdb library? Is there any change needed there, or is it just the same as it is now?

**Comment by demfabris** [comment]
Its the same, no usage changes.

**Comment by tobiemh** [comment]
Awesome!

**Comment by tobiemh** [comment]
Is this PR ready to merge as is?

**Comment by demfabris** [comment]
We can merge it but this new version cannot make into `surrealdb` yet as we first need to implement zero-copy deserialization in `storekey`.
Currently we get an error
```
error: implementation of `Deserialize` is not general enough
 --> lib/src/key/ns.rs:4:75
  |
4 | #[derive(Clone, Debug, Eq, PartialEq, PartialOrd, Serialize, Deserialize, Key)]
  |                                                                           ^^^ implementation of `Deserialize` is not general enough
  |
  = note: `Ns<'_>` must implement `Deserialize<'0>`, for any lifetime `'0`...
  = note: ...but `Ns<'_>` actually implements `Deserialize<'1>`, for some specific lifetime `'1`
  = note: this error originates in the derive macro `Key` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `surrealdb` due to previous error
```

**Comment by demfabris** [comment]
Related: https://github.com/surrealdb/storekey/pull/1

**Comment by demfabris** [comment]
Bumped version, ready to merge

**Comment by demfabris** [comment]
Ready to merge

**Pull request merged**
